### ISSUE TITLE
About totalRecords

### ISSUE THREAD

**Issue by wuly12345** [NikoGit/SNKRSMonitor#2]
调试的过程中， 发现一个问题， 就是一些已经发售的也会作为发售更新提示，程序拿到totalRecords的值是769， 通过SNKRS 抓包对比， 手机SNKRS 拿到的值是803.  但没有找到根本原因导致这一差异。

**Comment by wuly12345** [comment]
应该是提交参数的不同， 但是有个以为，如果提交参数为orderBy=lastUpdated, 返回的JSON 数据是没有SNKRS PASS信息 的， 如果提交参数为orderBy=published，是有SNKRS PASS 信息的， 所以是不是每次循环刷新的时候使用参数orderBy=published， 更能货到产品更新的消息？？

**Comment by NikoGit** [comment]
不是 只是排序不同,一个是按照发布顺序，一个是按照更新顺序，所有thread都会有的。

> 应该是提交参数的不同， 但是有个以为，如果提交参数为orderBy=lastUpdated, 返回的JSON 数据是没有SNKRS PASS信息 的， 如果提交参数为orderBy=published，是有SNKRS PASS 信息的， 所以是不是每次循环刷新的时候使用参数orderBy=published， 更能货到产品更新的消息？？

**Comment by NikoGit** [comment]
部分信息可能需要登录snkrs账号才看得见

> 调试的过程中， 发现一个问题， 就是一些已经发售的也会作为发售更新提示，程序拿到totalRecords的值是769， 通过SNKRS 抓包对比， 手机SNKRS 拿到的值是803. 但没有找到根本原因导致这一差异。
